spring:
  redis:
    database: 0 #Redis索引0~15，默认为0
    host: 192.168.75.131
    post: 6379
    timeout: 10000ms #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接